### ISSUE TITLE
Logic/UI issue

### ISSUE THREAD

**Issue by RichiV24** [HRTyrell/FEC#60]
Description
The stars in the product cards seem to shift depending on the image.

Screenshots
<img width="1288" alt="Screen Shot 2022-10-29 at 12 14 23 PM" src="https://user-images.githubusercontent.com/106782397/198844950-f0056603-686d-4f8b-aa4e-d19c061c379a.png">

You could probably just add it in with the rest of the product info or have a set height for all of the images

**Comment by gthellter** [comment]
Fixed in the most recent pull request
