### ISSUE TITLE
Logic issue#2

### ISSUE THREAD

**Issue by RichiV24** [HRTyrell/FEC#61]
Description
The back button still appears with no related products

Screenshots
<img width="1286" alt="Screen Shot 2022-10-29 at 12 27 03 PM" src="https://user-images.githubusercontent.com/106782397/198845122-b9f3ca21-4a09-4f43-bb1f-4b95583969d5.png">

To Reproduce
This happened with the infinity stone and it not having anything related to it 

Tasks
Add a condition to check if related products exist

**Comment by gthellter** [comment]
Fixed in most recent pull request
